<?php
declare(strict_types=1);
require __DIR__.'/../src/lib.php';
ob_start();st_load();register_shutdown_function('st_save');
$path='/'.trim((string)parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');$M=$_SERVER['REQUEST_METHOD'];
if($M==='POST')csrf_check();
$P=fn(string $k)=>trim((string)($_POST[$k]??''));
try{
if($path==='/health'){echo 'ok';exit;}
if($path==='/'){
 $pop=q(PSEL." WHERE p.active ORDER BY p.sales DESC,p.id DESC LIMIT 4")->fetchAll();$new=q(PSEL." WHERE p.active ORDER BY p.created_at DESC LIMIT 4")->fetchAll();$promo=q(PSEL." WHERE p.active AND p.promo_price IS NOT NULL ORDER BY p.id DESC LIMIT 4")->fetchAll();
 $s=fn($t,$r)=>$r?'<h2>'.$t.'</h2><div class="grid">'.implode('',array_map('card',$r)).'</div>':'';
 echo '';page('Accueil','</main><section class="hero"><div class="w"><h1>'.e(env('APP_NAME','Boutique')).'</h1><p>Vos produits préférés, livrés partout en Tunisie. Paiement à la livraison.</p><a class="btn o" href="/produits">Voir les produits</a> '.socials().'</div></section><main class="w">'.$s('Produits populaires',$pop).$s('Nouveaux produits',$new).$s('Promotions',$promo));exit;}
if($path==='/produits'){
 $w=['p.active'];$a=[];if($s=trim($_GET['q']??'')){$w[]='(p.name ILIKE :q OR p.description ILIKE :q)';$a['q']="%$s%";}if($c=$_GET['cat']??''){$w[]='c.slug=:c';$a['c']=$c;}
 $ord=['asc'=>'p.price ASC','desc'=>'p.price DESC'][$_GET['tri']??'']??'p.id DESC';$pp=12;$pg=max(1,(int)($_GET['page']??1));$W=implode(' AND ',$w);
 $tot=(int)q("SELECT count(*) FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE $W",$a)->fetchColumn();
 $rows=q(PSEL." WHERE $W ORDER BY $ord LIMIT $pp OFFSET ".(($pg-1)*$pp),$a)->fetchAll();
 $co='<option value="">Toutes catégories</option>';foreach(q("SELECT name,slug FROM categories ORDER BY name")->fetchAll() as $x)$co.='<option value="'.e($x['slug']).'"'.($c===$x['slug']?' selected':'').'>'.e($x['name']).'</option>';
 $h='<h1>Produits</h1><form class="grid" method="get"><input name="q" placeholder="Rechercher…" value="'.e($s).'"><select name="cat">'.$co.'</select><select name="tri"><option value="">Plus récents</option><option value="asc"'.(($_GET['tri']??'')==='asc'?' selected':'').'>Prix croissant</option><option value="desc"'.(($_GET['tri']??'')==='desc'?' selected':'').'>Prix décroissant</option></select><button class="btn">Filtrer</button></form><br><div class="grid">'.implode('',array_map('card',$rows)).'</div>'.($rows?'':'<p>Aucun produit.</p>').'<p class="pg">';
 for($i=1;$i<=max(1,(int)ceil($tot/$pp));$i++)$h.='<a class="'.($i===$pg?'on':'').'" href="?'.e(http_build_query(array_merge($_GET,['page'=>$i]))).'">'.$i.'</a>';
 page('Produits',$h.'</p>');exit;}
if(preg_match('#^/produit/([a-z0-9-]+)$#',$path,$m)){
 $p=q(PSEL." WHERE p.slug=? AND p.active",[$m[1]])->fetch();if(!$p){http_response_code(404);page('Introuvable','<h1>Produit introuvable</h1>');exit;}
 $im=q("SELECT url FROM product_images WHERE product_id=? ORDER BY position,id",[$p['id']])->fetchAll(PDO::FETCH_COLUMN);$g='';foreach($im as $i=>$u)$g.='<img '.($i?'loading="lazy" ':'').'style="width:100%;border-radius:12px;margin-bottom:8px" alt="'.e($p['name']).'" src="'.e(img($u,800)).'">';
 $now=$p['promo_price']??$p['price'];$wa=env('WHATSAPP_NUMBER');
 $h='<div class="two"><div>'.$g.'</div><div><h1>'.e($p['name']).'</h1><p>'.e($p['cat']).'</p><p class="pr" style="font-size:1.5rem">'.tnd($now).($p['promo_price']!==null?'<span class="old">'.tnd($p['price']).'</span>':'').'</p><p>'.($p['stock']>0?'<span class="bd">En stock ('.$p['stock'].')</span>':'<span class="bd r">Rupture de stock</span>').'</p><p>'.nl2br(e($p['description'])).'</p>';
 if($p['stock']>0)$h.='<form method="post" action="/panier/add">'.csrf().'<input type="hidden" name="id" value="'.$p['id'].'"><label>Quantité</label><input type="number" name="qty" value="1" min="1" max="'.$p['stock'].'"><br><br><button class="btn">Ajouter au panier</button></form><br>';
 if($wa)$h.='<a class="btn g" target="_blank" rel="noopener" href="https://wa.me/'.e(preg_replace('/\D/','',$wa)).'?text='.rawurlencode('Bonjour, je suis intéressé par : '.$p['name']).'">Commander sur WhatsApp</a>';
 page($p['name'],$h.'</div></div>',mb_substr(strip_tags($p['description']),0,150));exit;}
if($path==='/panier/add'&&$M==='POST'){$id=(int)$P('id');$n=max(1,(int)($_POST['qty']??1));$GLOBALS['S']['cart'][$id]=min(99,($GLOBALS['S']['cart'][$id]??0)+$n);flash('Produit ajouté au panier.');go('/panier');}
if($path==='/panier/update'&&$M==='POST'){$id=(int)$P('id');$n=(int)$P('qty');if($n<1)unset($GLOBALS['S']['cart'][$id]);else $GLOBALS['S']['cart'][$id]=min(99,$n);go('/panier');}
$cart=function(){$c=$GLOBALS['S']['cart']??[];if(!$c)return[[],0.0];$in=implode(',',array_map('intval',array_keys($c)));$rows=q("SELECT id,name,price,promo_price,stock FROM products WHERE active AND id IN($in)")->fetchAll();$t=0.0;foreach($rows as &$r){$r['qty']=min($c[$r['id']],$r['stock']);$r['u']=(float)($r['promo_price']??$r['price']);$r['sub']=$r['u']*$r['qty'];$t+=$r['sub'];}return[$rows,$t];};
if($path==='/panier'){[$rows,$t]=$cart();$h='<h1>Panier</h1>';if(!$rows)$h.='<p>Votre panier est vide.</p>';else{$h.='<div class="ov"><table><tr><th>Produit</th><th>Prix</th><th>Qté</th><th>Sous-total</th><th></th></tr>';foreach($rows as $r)$h.='<tr><td>'.e($r['name']).'</td><td>'.tnd($r['u']).'</td><td><form method="post" action="/panier/update" style="display:flex;gap:4px">'.csrf().'<input type="hidden" name="id" value="'.$r['id'].'"><input type="number" name="qty" value="'.$r['qty'].'" min="0" max="'.$r['stock'].'" style="width:70px"><button class="btn s">OK</button></form></td><td>'.tnd($r['sub']).'</td><td><form method="post" action="/panier/update">'.csrf().'<input type="hidden" name="id" value="'.$r['id'].'"><input type="hidden" name="qty" value="0"><button class="btn s">✕</button></form></td></tr>';$h.='</table></div><h2>Total : '.tnd($t).'</h2><a class="btn o" href="/commande">Passer la commande</a>';}page('Panier',$h);exit;}
if($path==='/commande'){[$rows,$t]=$cart();if(!$rows)go('/panier');$err='';
 if($M==='POST'){$f=['full_name','phone','address','governorate','city'];$ok=true;foreach($f as $k)if($P($k)==='')$ok=false;
  if(!$ok||!preg_match('/^[0-9+ ]{8,15}$/',$P('phone'))||!in_array($P('governorate'),gouvernorats(),true))$err='Veuillez vérifier les champs du formulaire.';
  else{$pdo=db();$pdo->beginTransaction();try{$tot=0.0;foreach($rows as $r){if($r['qty']<1||!q("UPDATE products SET stock=stock-?,sales=sales+? WHERE id=? AND active AND stock>=?",[$r['qty'],$r['qty'],$r['id'],$r['qty']])->rowCount())throw new RuntimeException('stock');$tot+=$r['sub'];}
   $no='CMD-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(3)));q("INSERT INTO orders(number,full_name,phone,address,governorate,city,notes,total) VALUES(?,?,?,?,?,?,?,?)",[$no,$P('full_name'),$P('phone'),$P('address'),$P('governorate'),$P('city'),$P('notes'),$tot]);$oid=(int)$pdo->lastInsertId('orders_id_seq');
   foreach($rows as $r)q("INSERT INTO order_items(order_id,product_id,name,price,qty) VALUES(?,?,?,?,?)",[$oid,$r['id'],$r['name'],$r['u'],$r['qty']]);$pdo->commit();$GLOBALS['S']['cart']=[];go('/confirmation/'.$no);}
   catch(RuntimeException $x){$pdo->rollBack();$err='Stock insuffisant pour un produit, merci de mettre à jour votre panier.';}}}
 $go='';foreach(gouvernorats() as $g)$go.='<option'.($P('governorate')===$g?' selected':'').'>'.e($g).'</option>';$sum='';foreach($rows as $r)$sum.='<li>'.e($r['name']).' × '.$r['qty'].' — '.tnd($r['sub']).'</li>';
 page('Commande',($err?'<p class="err">'.e($err).'</p>':'').'<h1>Commande</h1><div class="two"><form method="post">'.csrf().'<label>Nom et prénom</label><input name="full_name" required value="'.e($P('full_name')).'"><label>Téléphone</label><input name="phone" required value="'.e($P('phone')).'"><label>Adresse</label><textarea name="address" required>'.e($P('address')).'</textarea><label>Gouvernorat</label><select name="governorate" required><option value="">Choisir…</option>'.$go.'</select><label>Ville</label><input name="city" required value="'.e($P('city')).'"><label>Informations supplémentaires</label><textarea name="notes">'.e($P('notes')).'</textarea><br><button class="btn o">Confirmer (paiement à la livraison)</button></form><div><h2>Votre commande</h2><ul>'.$sum.'</ul><h2>Total : '.tnd($t).'</h2></div></div>');exit;}
if(preg_match('#^/confirmation/(CMD-[0-9A-F-]+)$#',$path,$m)){$o=q("SELECT * FROM orders WHERE number=?",[$m[1]])->fetch();if(!$o){http_response_code(404);exit;}$it=q("SELECT * FROM order_items WHERE order_id=?",[$o['id']])->fetchAll();$l='';foreach($it as $i)$l.='<li>'.e($i['name']).' × '.$i['qty'].' — '.tnd($i['price']*$i['qty']).'</li>';
 page('Confirmation','<h1>Merci pour votre commande !</h1><p class="flash">Commande n° <b>'.e($o['number']).'</b> enregistrée. Nous vous appellerons pour confirmer la livraison.</p><ul>'.$l.'</ul><h2>Total à payer à la livraison : '.tnd($o['total']).'</h2><p>Livraison : '.e($o['full_name']).', '.e($o['phone']).'<br>'.e($o['address']).', '.e($o['city']).', '.e($o['governorate']).'</p>');exit;}
if($path==='/contact'){if($M==='POST'&&$P('name')&&filter_var($P('email'),FILTER_VALIDATE_EMAIL)&&$P('body')){q("INSERT INTO messages(name,email,body) VALUES(?,?,?)",[$P('name'),$P('email'),$P('body')]);flash('Message envoyé, merci !');go('/contact');}
 page('Contact','<h1>Contact</h1><div class="two"><div><p>Tél : '.e(env('SHOP_PHONE','')).'</p><p>Email : '.e(env('SHOP_EMAIL','')).'</p><p>'.e(env('SHOP_ADDRESS','')).'</p><p>'.socials().'</p></div><form method="post">'.csrf().'<label>Nom</label><input name="name" required><label>Email</label><input type="email" name="email" required><label>Message</label><textarea name="body" required></textarea><br><button class="btn">Envoyer</button></form></div>');exit;}
if($path==='/sitemap.xml'){header('Content-Type: application/xml');$b=rtrim((string)env('APP_URL',''),'/');echo '<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"><url><loc>'.e($b).'/</loc></url><url><loc>'.e($b).'/produits</loc></url>';foreach(q("SELECT slug FROM products WHERE active")->fetchAll(PDO::FETCH_COLUMN) as $s)echo '<url><loc>'.e($b).'/produit/'.e($s).'</loc></url>';echo '</urlset>';exit;}
if(str_starts_with($path,'/admin')){require __DIR__.'/../src/admin.php';exit;}
http_response_code(404);page('Page introuvable','<h1>Page introuvable</h1>');
}catch(Throwable $x){error_log((string)$x);ob_clean();http_response_code(500);echo 'Erreur serveur.';}
