<?php
// Inclus par public/index.php ($path, $M, $P disponibles)
$ST=['nouvelle'=>'Nouvelle','confirmee'=>'Confirmée','en_preparation'=>'En préparation','expediee'=>'Expédiée','livree'=>'Livrée','annulee'=>'Annulée'];
$nav='<p><a href="/admin">Commandes</a> · <a href="/admin/produits">Produits</a> · <a href="/admin/categories">Catégories</a> · <form method="post" action="/admin/logout" style="display:inline">'.csrf().'<button class="btn s">Déconnexion</button></form></p>';
if($path==='/admin/login'){$err='';if($M==='POST'){$u=q("SELECT * FROM users WHERE email=? AND is_admin",[$P('email')])->fetch();usleep(300000);if($u&&password_verify($P('password'),$u['password'])){$GLOBALS['S']['admin']=(int)$u['id'];go('/admin');}$err='<p class="err">Identifiants invalides.</p>';}
 page('Admin',$err.'<h1>Connexion admin</h1><form method="post" style="max-width:360px">'.csrf().'<label>Email</label><input type="email" name="email" required><label>Mot de passe</label><input type="password" name="password" required><br><br><button class="btn">Se connecter</button></form>');return;}
admin();
if($path==='/admin/logout'){unset($GLOBALS['S']['admin']);go('/');}
if($path==='/admin'){$r=q("SELECT * FROM orders ORDER BY created_at DESC LIMIT 100")->fetchAll();$h=$nav.'<h1>Commandes</h1><div class="ov"><table><tr><th>N°</th><th>Client</th><th>Total</th><th>Statut</th><th></th></tr>';foreach($r as $o)$h.='<tr><td>'.e($o['number']).'</td><td>'.e($o['full_name']).'</td><td>'.tnd($o['total']).'</td><td>'.e($ST[$o['status']]).'</td><td><a href="/admin/commandes/'.$o['id'].'">Détails</a></td></tr>';page('Commandes',$h.'</table></div>');return;}
if(preg_match('#^/admin/commandes/(\d+)$#',$path,$m)){$o=q("SELECT * FROM orders WHERE id=?",[$m[1]])->fetch();if(!$o){http_response_code(404);return;}
 if($M==='POST'&&isset($ST[$P('status')])){q("UPDATE orders SET status=? WHERE id=?",[$P('status'),$o['id']]);flash('Statut mis à jour.');go($path);}
 $l='';foreach(q("SELECT * FROM order_items WHERE order_id=?",[$o['id']])->fetchAll() as $i)$l.='<li>'.e($i['name']).' × '.$i['qty'].' — '.tnd($i['price']*$i['qty']).'</li>';$op='';foreach($ST as $k=>$v)$op.='<option value="'.$k.'"'.($o['status']===$k?' selected':'').'>'.$v.'</option>';
 page('Commande',$nav.'<h1>'.e($o['number']).'</h1><p>'.e($o['full_name']).' · '.e($o['phone']).'<br>'.e($o['address']).', '.e($o['city']).', '.e($o['governorate']).'<br>'.e($o['notes']).'</p><ul>'.$l.'</ul><h2>'.tnd($o['total']).'</h2><form method="post">'.csrf().'<select name="status">'.$op.'</select><br><br><button class="btn">Changer le statut</button></form>');return;}
if($path==='/admin/categories'){if($M==='POST'){if($P('del'))q("DELETE FROM categories WHERE id=?",[(int)$P('del')]);elseif($P('name')){if($P('id'))q("UPDATE categories SET name=?,slug=? WHERE id=?",[$P('name'),slugify($P('name')),(int)$P('id')]);else q("INSERT INTO categories(name,slug) VALUES(?,?) ON CONFLICT DO NOTHING",[$P('name'),slugify($P('name'))]);}go($path);}
 $h=$nav.'<h1>Catégories</h1>';foreach(q("SELECT * FROM categories ORDER BY name")->fetchAll() as $c)$h.='<form method="post" style="display:flex;gap:6px;margin-bottom:6px">'.csrf().'<input type="hidden" name="id" value="'.$c['id'].'"><input name="name" value="'.e($c['name']).'"><button class="btn s">Modifier</button><button class="btn s" name="del" value="'.$c['id'].'" onclick="return confirm(\'Supprimer ?\')">Supprimer</button></form>';
 page('Catégories',$h.'<h2>Ajouter</h2><form method="post" style="display:flex;gap:6px">'.csrf().'<input name="name" required><button class="btn">Ajouter</button></form>');return;}
if($path==='/admin/produits'){$h=$nav.'<h1>Produits</h1><a class="btn" href="/admin/produits/new">+ Nouveau</a><br><br><div class="ov"><table><tr><th>Nom</th><th>Prix</th><th>Promo</th><th>Stock</th><th></th></tr>';foreach(q("SELECT * FROM products ORDER BY id DESC")->fetchAll() as $p)$h.='<tr><td>'.e($p['name']).'</td><td>'.tnd($p['price']).'</td><td>'.($p['promo_price']!==null?tnd($p['promo_price']):'—').'</td><td>'.$p['stock'].'</td><td><a href="/admin/produits/'.$p['id'].'">Modifier</a></td></tr>';page('Produits',$h.'</table></div>');return;}
if(preg_match('#^/admin/produits/(new|\d+)$#',$path,$m)){$id=$m[1]==='new'?0:(int)$m[1];$p=$id?q("SELECT * FROM products WHERE id=?",[$id])->fetch():['name'=>'','category_id'=>null,'price'=>'','promo_price'=>null,'stock'=>0,'description'=>'','active'=>true];if($id&&!$p){http_response_code(404);return;}
 if($M==='POST'){
  if($P('delete')&&$id){q("DELETE FROM products WHERE id=?",[$id]);go('/admin/produits');}
  $pr=(float)str_replace(',','.',$P('price'));$pm=$P('promo_price')===''?null:(float)str_replace(',','.',$P('promo_price'));$stk=max(0,(int)$P('stock'));$cat=$P('category_id')?:null;
  if($P('name')===''||$pr<0||($pm!==null&&($pm<0||$pm>=$pr))){flash('Données invalides (le prix promo doit être inférieur au prix).');go($path);}
  if($id)q("UPDATE products SET name=?,category_id=?,price=?,promo_price=?,stock=?,description=?,active=?,updated_at=now() WHERE id=?",[$P('name'),$cat,$pr,$pm,$stk,$P('description'),isset($_POST['active'])?'true':'false',$id]);
  else{$id=(int)q("INSERT INTO products(name,slug,category_id,price,promo_price,stock,description,active) VALUES(?,?,?,?,?,?,?,?) RETURNING id",[$P('name'),slugify($P('name')).'-'.bin2hex(random_bytes(2)),$cat,$pr,$pm,$stk,$P('description'),isset($_POST['active'])?'true':'false'])->fetchColumn();}
  foreach((array)($_POST['del_img']??[]) as $d)q("DELETE FROM product_images WHERE id=? AND product_id=?",[(int)$d,$id]);
  if(!empty($_FILES['images']['name'][0]))foreach($_FILES['images']['name'] as $i=>$_){$u=upload_image(['error'=>$_FILES['images']['error'][$i],'size'=>$_FILES['images']['size'][$i],'tmp_name'=>$_FILES['images']['tmp_name'][$i]]);if($u)q("INSERT INTO product_images(product_id,url,position) VALUES(?,?,?)",[$id,$u,$i]);else flash('Une image a été refusée (JPG/PNG/WebP, 3 Mo max) ou le stockage est mal configuré.');}
  if(!isset($GLOBALS['S']['flash']))flash('Produit enregistré.');go('/admin/produits/'.$id);}
 $co='<option value="">—</option>';foreach(q("SELECT id,name FROM categories ORDER BY name")->fetchAll() as $c)$co.='<option value="'.$c['id'].'"'.((string)$p['category_id']===(string)$c['id']?' selected':'').'>'.e($c['name']).'</option>';
 $im='';if($id)foreach(q("SELECT id,url FROM product_images WHERE product_id=?",[$id])->fetchAll() as $i)$im.='<label style="display:inline-block;width:90px"><img src="'.e(img($i['url'],120)).'" width="80"><br><input type="checkbox" name="del_img[]" value="'.$i['id'].'" style="width:auto"> suppr.</label>';
 page('Produit',$nav.'<h1>'.($id?'Modifier':'Nouveau').' produit</h1><form method="post" enctype="multipart/form-data" style="max-width:600px">'.csrf().'<label>Nom</label><input name="name" required value="'.e($p['name']).'"><label>Catégorie</label><select name="category_id">'.$co.'</select><label>Prix (TND)</label><input name="price" required value="'.e($p['price']).'"><label>Prix promo (optionnel)</label><input name="promo_price" value="'.e($p['promo_price']).'"><label>Stock</label><input type="number" name="stock" min="0" value="'.e($p['stock']).'"><label>Description</label><textarea name="description" rows="5">'.e($p['description']).'</textarea><label><input type="checkbox" name="active" style="width:auto" '.($p['active']?'checked':'').'> Visible</label><label>Ajouter des images</label><input type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp"><p>'.$im.'</p><button class="btn">Enregistrer</button>'.($id?' <button class="btn s" name="delete" value="1" onclick="return confirm(\'Supprimer ce produit ?\')">Supprimer</button>':'').'</form>');return;}
http_response_code(404);
