<?php
declare(strict_types=1);
function env(string $k,$d=null){static $f;if($f===null){$f=[];$p=__DIR__.'/../.env';if(is_file($p))foreach(file($p,FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES) as $l){if($l[0]==='#'||!str_contains($l,'='))continue;[$a,$b]=explode('=',$l,2);$f[trim($a)]=trim($b,"\"' ");}}$v=getenv($k);return($v!==false&&$v!=='')?$v:($f[$k]??$d);}
function db():PDO{static $p;return $p??=new PDO('pgsql:host='.env('DB_HOST').';port='.env('DB_PORT','5432').';dbname='.env('DB_DATABASE').';sslmode='.env('DB_SSLMODE','require'),env('DB_USERNAME'),env('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>true]);}
function q(string $s,array $a=[]):PDOStatement{$st=db()->prepare($s);$st->execute($a);return $st;}
function e($s):string{return htmlspecialchars((string)$s,ENT_QUOTES,'UTF-8');}
function tnd($n):string{return number_format((float)$n,3,',',' ').' TND';}
function go(string $u){header('Location: '.$u,true,303);exit;}
function slugify(string $s):string{$s=strtolower(trim(preg_replace('/[^A-Za-z0-9]+/','-',iconv('UTF-8','ASCII//TRANSLIT',$s)),'-'));return $s?:'item';}
function st_load(){if(!env('APP_KEY'))throw new RuntimeException('APP_KEY manquant');$s=[];$c=$_COOKIE['st']??'';if(substr_count($c,'.')===1){[$d,$m]=explode('.',$c);if(hash_equals(hash_hmac('sha256',$d,env('APP_KEY')),$m))$s=json_decode(base64_decode($d),true)?:[];}$s['csrf']??=bin2hex(random_bytes(16));$GLOBALS['S']=$s;}
function st_save(){if(headers_sent())return;$d=base64_encode(json_encode($GLOBALS['S']));setcookie('st',$d.'.'.hash_hmac('sha256',$d,env('APP_KEY')),['path'=>'/','httponly'=>true,'samesite'=>'Lax','secure'=>!empty($_SERVER['HTTPS'])||($_SERVER['HTTP_X_FORWARDED_PROTO']??'')==='https']);}
function csrf():string{return '<input type="hidden" name="_t" value="'.e($GLOBALS['S']['csrf']).'">';}
function csrf_check(){if(!hash_equals($GLOBALS['S']['csrf'],(string)($_POST['_t']??''))){http_response_code(419);exit('Session expirée, rechargez la page.');}}
function flash(?string $m=null){if($m!==null){$GLOBALS['S']['flash']=$m;return '';}$f=$GLOBALS['S']['flash']??'';unset($GLOBALS['S']['flash']);return $f?'<p class="flash">'.e($f).'</p>':'';}
function admin(){if(empty($GLOBALS['S']['admin']))go('/admin/login');}
function img(?string $u,int $w=600):string{return $u?str_replace('/upload/','/upload/f_auto,q_auto,w_'.$w.'/',$u):'';}
function upload_image(array $f):?string{
 if(($f['error']??1)!==0||$f['size']>3*1048576)return null;
 $m=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!in_array($m,['image/jpeg','image/png','image/webp'],true))return null;
 $ts=time();$sig=sha1("folder=shop&timestamp=$ts".env('CLOUDINARY_API_SECRET'));
 $ch=curl_init('https://api.cloudinary.com/v1_1/'.env('CLOUDINARY_CLOUD_NAME').'/image/upload');
 curl_setopt_array($ch,[CURLOPT_POST=>1,CURLOPT_RETURNTRANSFER=>1,CURLOPT_TIMEOUT=>20,CURLOPT_POSTFIELDS=>['file'=>new CURLFile($f['tmp_name'],$m),'api_key'=>env('CLOUDINARY_API_KEY'),'timestamp'=>$ts,'folder'=>'shop','signature'=>$sig]]);
 $r=json_decode((string)curl_exec($ch),true);return $r['secure_url']??null;}
function gouvernorats():array{return['Ariana','Béja','Ben Arous','Bizerte','Gabès','Gafsa','Jendouba','Kairouan','Kasserine','Kébili','Le Kef','Mahdia','La Manouba','Médenine','Monastir','Nabeul','Sfax','Sidi Bouzid','Siliana','Sousse','Tataouine','Tozeur','Tunis','Zaghouan'];}
function socials():string{$o='';foreach(['FACEBOOK_URL'=>'Facebook','INSTAGRAM_URL'=>'Instagram','TIKTOK_URL'=>'TikTok'] as $k=>$n)if($u=env($k))$o.='<a class="soc" href="'.e($u).'" target="_blank" rel="noopener" aria-label="'.$n.'" title="'.$n.'">'.['Facebook'=>'f','Instagram'=>'ig','TikTok'=>'tt'][$n].'</a>';return $o;}
function page(string $t,string $body,string $desc=''){
 $n=e(env('APP_NAME','Boutique'));$c=array_sum($GLOBALS['S']['cart']??[]);$desc=e($desc?:'Boutique en ligne en Tunisie. Paiement à la livraison.');
 $cl='';foreach(q("SELECT name,slug FROM categories ORDER BY name")->fetchAll() as $x)$cl.='<a href="/produits?cat='.e($x['slug']).'">'.e($x['name']).'</a>';
 echo '<!doctype html><html lang="fr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'.e($t).' | '.$n.'</title><meta name="description" content="'.$desc.'"><meta property="og:title" content="'.e($t).'"><meta property="og:description" content="'.$desc.'"><meta property="og:type" content="website"><link rel="icon" href="data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 viewBox=%270 0 100 100%27%3E%3Ctext y=%27.9em%27 font-size=%2790%27%3E🛍️%3C/text%3E%3C/svg%3E"><style>
:root{--c:#0f766e;--c2:#f59e0b;--bg:#f8fafc;--t:#0f172a;--r:12px}*{box-sizing:border-box}body{margin:0;font:16px/1.5 system-ui,sans-serif;background:var(--bg);color:var(--t)}a{color:inherit}.w{max-width:1100px;margin:auto;padding:0 16px}
header{background:#fff;border-bottom:1px solid #e2e8f0;position:sticky;top:0;z-index:5}header .w{display:flex;flex-wrap:wrap;gap:8px 16px;align-items:center;padding:10px 16px}header nav{display:flex;flex-wrap:wrap;gap:14px;flex:1}.logo{font-weight:800;color:var(--c);text-decoration:none;font-size:1.3rem}
.soc{display:inline-grid;place-items:center;width:30px;height:30px;border-radius:50%;background:var(--c);color:#fff;text-decoration:none;font-size:12px;margin-right:4px}.dd{position:relative}.dd div{display:none;position:absolute;background:#fff;border:1px solid #e2e8f0;border-radius:8px;padding:8px;min-width:150px}.dd:hover div,.dd:focus-within div{display:block}.dd div a{display:block;padding:4px}
.btn{display:inline-block;background:var(--c);color:#fff;border:0;border-radius:var(--r);padding:10px 18px;font:inherit;font-weight:600;text-decoration:none;cursor:pointer}.btn.o{background:var(--c2)}.btn.g{background:#25d366}.btn.s{background:#64748b;padding:6px 12px}
.hero{background:linear-gradient(135deg,var(--c),#115e59);color:#fff;padding:48px 0}.hero h1{margin:0 0 8px;font-size:clamp(1.6rem,5vw,2.6rem)}.grid{display:grid;gap:16px;grid-template-columns:repeat(auto-fill,minmax(210px,1fr))}
.card{background:#fff;border-radius:var(--r);overflow:hidden;box-shadow:0 1px 4px #0001;display:flex;flex-direction:column}.card .im{aspect-ratio:1;background:#e2e8f0;display:block}.card img{width:100%;height:100%;object-fit:cover;display:block}.card .b{padding:12px;display:flex;flex-direction:column;gap:6px;flex:1}
.pr{font-weight:700;color:var(--c)}.old{text-decoration:line-through;color:#94a3b8;font-weight:400;margin-left:6px}.bd{font-size:12px;padding:2px 8px;border-radius:99px;background:#dcfce7;color:#166534;display:inline-block}.bd.r{background:#fee2e2;color:#991b1b}.bd.p{background:#fef3c7;color:#92400e}
input,select,textarea{width:100%;padding:10px;border:1px solid #cbd5e1;border-radius:8px;font:inherit}label{display:block;margin:10px 0 4px;font-weight:600}table{width:100%;border-collapse:collapse;background:#fff}td,th{padding:8px;border-bottom:1px solid #e2e8f0;text-align:left}.ov{overflow-x:auto}
.flash{background:#dcfce7;padding:10px;border-radius:8px}.err{background:#fee2e2;padding:10px;border-radius:8px}.two{display:grid;gap:24px;grid-template-columns:1fr}@media(min-width:760px){.two{grid-template-columns:1fr 1fr}}h2{margin-top:32px}footer{background:#0f172a;color:#cbd5e1;margin-top:48px;padding:32px 0}footer a{color:#fff}.pg a{padding:6px 12px;background:#fff;border-radius:6px;margin-right:4px;text-decoration:none}.pg a.on{background:var(--c);color:#fff}
</style></head><body><header><div class="w"><a class="logo" href="/">'.$n.'</a><nav><a href="/">Accueil</a><a href="/produits">Produits</a><span class="dd"><a href="#" tabindex="0">Catégories ▾</a><div>'.$cl.'</div></span><a href="/contact">Contact</a></nav><span>'.socials().'</span><a class="btn" href="/panier">Panier ('.$c.')</a></div></header><main class="w">'.flash().$body.'</main><footer><div class="w two"><div><b>'.$n.'</b><p>'.e(env('SHOP_ADDRESS','')).'</p><p>'.e(env('SHOP_PHONE','')).' · '.e(env('SHOP_EMAIL','')).'</p><p>'.socials().'</p></div><div><a href="/">Accueil</a> · <a href="/produits">Produits</a> · <a href="/contact">Contact</a><p>© '.date('Y').' '.$n.'. Tous droits réservés.</p></div></div></footer></body></html>';}
function card(array $p):string{$now=$p['promo_price']??$p['price'];$h='<article class="card"><a class="im" href="/produit/'.e($p['slug']).'">'.($p['img']?'<img loading="lazy" width="400" height="400" alt="'.e($p['name']).'" src="'.e(img($p['img'],400)).'">':'').'</a><div class="b"><div>'.($p['stock']>0?'<span class="bd">En stock</span>':'<span class="bd r">Rupture de stock</span>').($p['promo_price']!==null?' <span class="bd p">Promotion</span>':'').'</div><a href="/produit/'.e($p['slug']).'"><b>'.e($p['name']).'</b></a><div class="pr">'.tnd($now).($p['promo_price']!==null?'<span class="old">'.tnd($p['price']).'</span>':'').'</div>';
 if($p['stock']>0)$h.='<form method="post" action="/panier/add">'.csrf().'<input type="hidden" name="id" value="'.$p['id'].'"><button class="btn s">Ajouter au panier</button></form>';return $h.'</div></article>';}
const PSEL="SELECT p.*,c.name cat,(SELECT url FROM product_images i WHERE i.product_id=p.id ORDER BY position,id LIMIT 1) img FROM products p LEFT JOIN categories c ON c.id=p.category_id";
